[server]
headless = true
enableCORS = false
address = "0.0.0.0"
port = $PORT

[theme]
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"